version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-app
      - run: npm ci
      - save_cache:
          key: v1-app
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record --key a32273cb-9104-4849-a30b-b479bead9494
